### ISSUE TITLE
监听到Key：undefined 的活动

### ISSUE THREAD

**Issue by wxrbbs** [goodmangll/falco-docker#1]
###### request end ######
debug: 2024-04-00 23:54:45: 	监听到Key：undefined 的活动，其用户ID为：26d6af9953534c079bd6fb673ba754e5，所对应的盘为:/alyOpen
debug: 2024-04-00 23:55:19: 	开始对视频临时文件目录进行清除......
debug: 2024-04-00 23:55:19: 	获取正在播放的视频......
debug: 2024-04-00 23:55:19: 	遍历所有盘的临时文件目录，清除不需要的临时文件......
debug: 2024-04-00 23:55:19: 	开始扫描 /alyOpen/falcoTmp 中无用的临时文件
debug: 2024-04-00 23:55:19: 	/alyOpen/falcoTmp 中没有文件不需要清除
info: 2024-04-00 23:56:08: 	开始启动......
info: 2024-04-00 23:56:08: 	初始化nginx......
info: 2024-04-00 23:56:08: 	nginx 启动成功！
info: 2024-04-00 23:56:08: 	初始化视频临时文件目录......
info: 2024-04-00 23:56:09: 	启动视频临时文件目录自动清除服务......
debug: 2024-04-00 23:56:09: 	开始对视频临时文件目录进行清除......
debug: 2024-04-00 23:56:09: 	获取正在播放的视频......
debug: 2024-04-00 23:56:09: 	遍历所有盘的临时文件目录，清除不需要的临时文件......
debug: 2024-04-00 23:56:09: 	开始扫描 /alyOpen/falcoTmp 中无用的临时文件
info: 2024-04-00 23:56:09: 	fileRawUrlProxy启动成功！
info: 2024-04-00 23:56:09: 	Server is running on http://localhost:13000
debug: 2024-04-00 23:56:09: 	/alyOpen/falcoTmp 中没有文件不需要清除
debug: 2024-04-00 23:56:21: 	###### request start ######

debug: 2024-04-00 23:56:21: 	监听到Key：undefined 的活动，其用户ID为：26d6af9953534c079bd6fb673ba754e5，所对应的盘为:/alyOpen
debug: 2024-04-00 23:56:21: 	###### request start ######

你好请问这个监控到Key：undefined 为什么是未定义    问题出在哪里？ 我这里是jellyfin的
我用的是cd2挂载本地，用本地绝对路径的strm播放
config.yaml 里参数设置检查过也是对的  alist的log也看了，api接口都是没有问题

还有新版本说falcoTmp可以自动创建，我启动后并没有自动创建，是自己创建的。

**Comment by goodmangll** [comment]
请提供下jellyfin用的什么客户端。可以尝试下更新镜像。

**Comment by goodmangll** [comment]
> ```
>     ###### request end ######
> ```
> 
> debug: 2024-04-00 23:54:45: 监听到Key：undefined 的活动，其用户ID为：26d6af9953534c079bd6fb673ba754e5，所对应的盘为:/alyOpen debug: 2024-04-00 23:55:19: 开始对视频临时文件目录进行清除...... debug: 2024-04-00 23:55:19: 获取正在播放的视频...... debug: 2024-04-00 23:55:19: 遍历所有盘的临时文件目录，清除不需要的临时文件...... debug: 2024-04-00 23:55:19: 开始扫描 /alyOpen/falcoTmp 中无用的临时文件 debug: 2024-04-00 23:55:19: /alyOpen/falcoTmp 中没有文件不需要清除 info: 2024-04-00 23:56:08: 开始启动...... info: 2024-04-00 23:56:08: 初始化nginx...... info: 2024-04-00 23:56:08: nginx 启动成功！ info: 2024-04-00 23:56:08: 初始化视频临时文件目录...... info: 2024-04-00 23:56:09: 启动视频临时文件目录自动清除服务...... debug: 2024-04-00 23:56:09: 开始对视频临时文件目录进行清除...... debug: 2024-04-00 23:56:09: 获取正在播放的视频...... debug: 2024-04-00 23:56:09: 遍历所有盘的临时文件目录，清除不需要的临时文件...... debug: 2024-04-00 23:56:09: 开始扫描 /alyOpen/falcoTmp 中无用的临时文件 info: 2024-04-00 23:56:09: fileRawUrlProxy启动成功！ info: 2024-04-00 23:56:09: Server is running on http://localhost:13000 debug: 2024-04-00 23:56:09: /alyOpen/falcoTmp 中没有文件不需要清除 debug: 2024-04-00 23:56:21: ###### request start ######
> 
> debug: 2024-04-00 23:56:21: 监听到Key：undefined 的活动，其用户ID为：26d6af9953534c079bd6fb673ba754e5，所对应的盘为:/alyOpen debug: 2024-04-00 23:56:21: ###### request start ######
> 
> 你好请问这个监控到Key：undefined 为什么是未定义 问题出在哪里？ 我这里是jellyfin的 我用的是cd2挂载本地，用本地绝对路径的strm播放 config.yaml 里参数设置检查过也是对的 alist的log也看了，api接口都是没有问题
> 
> 还有新版本说falcoTmp可以自动创建，我启动后并没有自动创建，是自己创建的。

请提供下jellyfin用的什么客户端。可以尝试下更新镜像。

**Comment by wxrbbs** [comment]
jellyfin服务端：image: nyanmisaka/jellyfin:latest 最新版本1.8.13 客户端pc网页版调用pot，手机安卓客户端为jellyfin官方客户端

**Comment by goodmangll** [comment]
> jellyfin服务端：image: nyanmisaka/jellyfin:latest 最新版本1.8.13 客户端pc网页版调用pot，手机安卓客户端为jellyfin官方客户端

需要更多的日志上下文，方便留一个邮箱吗

**Comment by wxrbbs** [comment]
wxrbbs@qq.com
